<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BunLabs.NAudio.Flac" Version="2.0.1" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Kinda Girl %28Separated%29\bass.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\drums.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\other.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\vocals.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\crash_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\hihat_open01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\kick_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\ride_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\rim_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\clear_loop_samples\snare_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\crash_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\hihat_open01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\hihat_open_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\kick_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\kick_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\ride_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\ride_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\ride_short01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\rim_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\rim_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\snare_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\snare_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\effect_loop_samples\snare_03.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\scratch_loop_samples\scratch_down_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\scratch_loop_samples\scratch_down_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\scratch_loop_samples\scratch_up_01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\scratch_loop_samples\scratch_up_02.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\start_loop_samples\kick01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\start_loop_samples\snare01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\start_loop_samples\snare_rattle01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\start_loop_samples\tom_high01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Kinda Girl %28Separated%29\_Samples\start_loop_samples\tom_mid01.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
